#! perl
# Copyright (C) 2009, Parrot Foundation.

use strict;
use warnings;
use 5.008;

use Parrot::Test::Harness language => 'xml';

# Local Variables:
#   mode: cperl
#   cperl-indent-level: 4
#   fill-column: 100
# End:
# vim: expandtab shiftwidth=4:

